# Top and HDMI stuff
VERILOG += ./top.v \
	./ecp5pll.sv \
	./hdmi.v

# TT design
VERILOG += \
	../src/audiotrack.v \
	../src/cordic2step.v \
	../src/donut.v \
	../src/donuthit.v \
	../src/recip16.v \
	../src/rom.v \
	../src/songrom.v \
	../src/step3vec.v \
	../src/vgademo.v


DEVICE=85k

include ulx3s.mk

